[package]
name = "epp-proxy"
version = "0.1.0"
authors = ["Q <q@misell.cymru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["rt-core", "dns", "tcp", "macros", "time", "io-util", "fs", "signal"] }
futures = "0.3"
log = "0.4"
pretty_env_logger = "0.4"
native-tls = "0.2"
tokio-tls = "0.3.0"
quick-xml = { version = "0.18", features = ["serialize"]}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
time = "0.1"
uuid = { version = "0.8", features = ["v4"] }
hex = "0.4"
regex = "1"
tonic = { version = "0.2", features = ["transport", "tls"] }
prost = "0.6"
prost-types = "0.6"
clap = "2.33"
base64 = "0.12"
xml_serde = { git = "https://github.com/as207960/xml-serde", rev = "b816f2a25e912f8261c727711ac424d47b279cb1" }
#xml_serde = { path = "../xml_serde" }
rust-keycloak = { git = "https://github.com/TheEnbyperor/rust-keycloak", rev = "b4f76d59331d991909d199dca65e269e391dac82" }
dotenv = "0.9.0"
tower-service = "0.3"
http = "0.2"
sys-info = "0.9"
sentry = { version = "0.21.0", features = ["log"] }

[build-dependencies]
tonic-build = "0.2"
built = { version = "0.4", features = ["git2"] }
