apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: epp-proxy-cert
spec:
  secretName: epp-proxy-tls
  duration: 8760h
  renewBefore: 360h
  commonName: epp-proxy
  subject:
    organizations:
      - AS207960
  isCA: false
  privateKey:
    size: 4096
    algorithm: RSA
    encoding: PKCS1
  usages:
    - server auth
  dnsNames:
    - epp-proxy
    - epp-proxy.default
  issuerRef:
    name: epp-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: epp-proxy-test-primary-cert
spec:
  secretName: epp-proxy-test-primary-tls
  duration: 8760h
  renewBefore: 360h
  commonName: epp-proxy-test-primary
  subject:
    organizations:
      - AS207960
  isCA: false
  privateKey:
    size: 4096
    algorithm: RSA
    encoding: PKCS1
  usages:
    - server auth
  dnsNames:
    - epp-proxy-test-primary
    - epp-proxy-test-primary.default
  issuerRef:
    name: epp-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: epp-proxy-test-secondary-cert
spec:
  secretName: epp-proxy-test-secondary-tls
  duration: 8760h
  renewBefore: 360h
  commonName: epp-proxy-test-secondary
  subject:
    organizations:
      - AS207960
  isCA: false
  privateKey:
    size: 4096
    algorithm: RSA
    encoding: PKCS1
  usages:
    - server auth
  dnsNames:
    - epp-proxy-test-secondary
    - epp-proxy-test-secondary.default
  issuerRef:
    name: epp-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: epp-client-cert
spec:
  secretName: epp-client-tls
  duration: 8760h
  renewBefore: 360h
  commonName: as207960-registrar
  subject:
    countries:
      - GB
    localities:
      - Cymru
    organizations:
      - AS207960 Cyfyngedig
  isCA: false
  privateKey:
    size: 4096
    algorithm: RSA
    encoding: PKCS1
  usages:
    - client auth
  issuerRef:
    name: epp-client-issuer
    kind: Issuer
    group: cert-manager.io
  keystores:
    pkcs12:
      create: true
      profile: Modern2023
      passwordSecretRef:
        name: epp-client-tls-password
        key: password
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: epp-client-issuer
spec:
  selfSigned: {}