apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: epp-proxy-cert
spec:
  secretName: epp-proxy-tls
  duration: 2160h
  renewBefore: 360h
  commonName: epp-proxy
  subject:
    organizations:
      - AS207960
  isCA: false
  privateKey:
    size: 4096
    algorithm: RSA
    encoding: PKCS1
  usages:
    - server auth
  dnsNames:
    - epp-proxy
    - epp-proxy.default
  issuerRef:
    name: epp-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: epp-proxy-test-primary-cert
spec:
  secretName: epp-proxy-test-primary-tls
  duration: 2160h
  renewBefore: 360h
  commonName: epp-proxy-test-primary
  subject:
    organizations:
      - AS207960
  isCA: false
  privateKey:
    size: 4096
    algorithm: RSA
    encoding: PKCS1
  usages:
    - server auth
  dnsNames:
    - epp-proxy-test-primary
    - epp-proxy-test-primary.default
  issuerRef:
    name: epp-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: epp-proxy-test-secondary-cert
spec:
  secretName: epp-proxy-test-secondary-tls
  duration: 2160h
  renewBefore: 360h
  commonName: epp-proxy-test-secondary
  subject:
    organizations:
      - AS207960
  isCA: false
  privateKey:
    size: 4096
    algorithm: RSA
    encoding: PKCS1
  usages:
    - server auth
  dnsNames:
    - epp-proxy-test-secondary
    - epp-proxy-test-secondary.default
  issuerRef:
    name: epp-ca-issuer
    kind: Issuer
    group: cert-manager.io
