kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: epp-proxy-test-primary-log
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: epp-proxy-test-conf
data:
  CLIENT_ID: "epp-proxy"
  OAUTH_WELL_KNOWN: "https://sso.as207960.net/auth/realms/test/.well-known/openid-configuration"
  TLS_CERT_FILE: "/tls/tls.crt"
  TLS_KEY_FILE: "/tls/tls.key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epp-proxy-test-primary
  labels:
    app: epp-proxy-test-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epp-proxy-test-primary
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"pi-epp-ip6-ippool\"]"
      labels:
        app: epp-proxy-test-primary
    spec:
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: epp-proxy-test-primary-log
        - name: conf
          secret:
            secretName: epp-proxy-test-primary-conf
        - name: tls-keys
          secret:
            secretName: epp-proxy-test-primary-tls
        - name: priv-keys
          secret:
            secretName: epp-proxy-priv
      containers:
        - name: epp-proxy
          image: as207960/epp-proxy:(version)
          imagePullPolicy: Always
          args: ["--log",  "/log", "--conf", "/conf", "--listen", "[::]:50051"]
          ports:
            - containerPort: 50051
          volumeMounts:
            - mountPath: "/conf"
              name: conf
            - mountPath: "/log"
              name: logs
            - mountPath: "/tls"
              name: tls-keys
            - mountPath: "/priv"
              name: priv-keys
          env:
            - name: RUST_LOG
              value: info
          envFrom:
            - configMapRef:
                name: epp-proxy-test-conf
            - secretRef:
                name: epp-proxy-test-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: epp-proxy-test-primary
  labels:
    app: epp-proxy-test-primary
spec:
  selector:
    app: epp-proxy-test-primary
  ports:
    - port: 50051
      targetPort: 50051
