kind: ConfigMap
apiVersion: v1
metadata:
  name: epp-proxy-conf
data:
  CLIENT_ID: "epp-proxy"
  OAUTH_WELL_KNOWN: "https://sso.as207960.net/auth/realms/master/.well-known/openid-configuration"
  TLS_CERT_FILE: "/tls/tls.crt"
  TLS_KEY_FILE: "/tls/tls.key"
  LOG_DRIVER: "s3"
  S3_ENDPOINT: "https://s3.as207960.net"
  S3_REGION: "garage"
  S3_BUCKET: "epp-proxy-logs"
  S3_ACCESS_KEY_ID: "GK55245894566f49fd280eaa8a"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epp-proxy
  labels:
    app: epp-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epp-proxy
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"pi-epp-ip6-ippool\"]"
      labels:
        app: epp-proxy
    spec:
      volumes:
        - name: conf
          secret:
            secretName: epp-proxy-conf
        - name: tls-keys
          secret:
            secretName: epp-proxy-tls
        - name: priv-keys
          secret:
            secretName: epp-proxy-priv
      containers:
        - name: epp-proxy
          image: as207960/epp-proxy:(version)
          imagePullPolicy: Always
          args: ["--log",  "/log", "--conf", "/conf", "--listen", "[::]:50051"]
          ports:
            - containerPort: 50051
          volumeMounts:
            - mountPath: "/conf"
              name: conf
            - mountPath: "/tls"
              name: tls-keys
            - mountPath: "/priv"
              name: priv-keys
          env:
            - name: RUST_LOG
              value: info
          envFrom:
            - configMapRef:
                name: epp-proxy-conf
            - secretRef:
                name: epp-proxy-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: epp-proxy
  labels:
    app: epp-proxy
spec:
  selector:
    app: epp-proxy
  ports:
    - port: 50051
      targetPort: 50051
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: epp-proxy
  annotations:
    cert-manager.io/cluster-issuer: "gts"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
spec:
  tls:
    - hosts:
        - epp-proxy.as207960.ltd.uk
      secretName: epp-proxy-pub-tls
  rules:
    - host: epp-proxy.as207960.ltd.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: epp-proxy
                port:
                  number: 50051
