name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: cargo check
    - name: Format
      run: cargo fmt --all
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Build docs
      run: cargo rustdoc -- --enable-index-page --document-private-items
    - name: Setup git
      run: git config --global user.name ${GITHUB_ACTOR} && git config --global user.email ${GITHUB_ACTOR}@users.noreply.github.com
    - name: Push docs
      run: mv target/doc docs && git add docs && git commit -m "Autogen docs" && git push
