name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: cargo check
    - name: Format
      run: cargo fmt --all
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Build docs
      run: cargo doc --document-private-items
    - name: Push docs
      run: mv target/doc docs && git add docs && git commit -m "Autogen docs"
